apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: workflow
    sesac.io/template-color: "#F97316"
    sesac.io/template-stack: Argo Workflows
  description: Spark Job이 포함된 기본 Argo Workflow를 생성합니다
  name: argo-workflows-basic
  title: Spark Job을 포함한 기본 Argo Workflow
spec:
  owner: guests
  type: service
  parameters:
    - title: 구성 옵션
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: 애플리케이션 이름
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          description: '중요: 개인 계정이 아닌 GitHub Organization 이름(예: SAMJOYAP)을 입력하세요. GitHub Apps는 Organization에서만 작동합니다.'
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP  # Update this to your GitHub Organization name after forking
        mainApplicationFile:
          type: string
          default: 'local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar'
          description: 메인 애플리케이션 파일 경로

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: This is an Argo Workflow with Spark Job

    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: create-argocd-app
      name: ArgoCD App 생성
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.name}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: ${{ steps['create-repo'].output.remoteUrl }}
        path: "manifests"

    - id: register
      name: Catalog 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Catalog에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
