apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.projectName }}
  description: Backstage 템플릿으로 생성된 Java 웹 프로젝트 (Apache + Spring Boot + ${{ values.buildTool | upper }})
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.owner }}/${{ values.repo }}
    argocd/app-name: ${{ values.projectName }}
    backstage.io/kubernetes-cluster: ${{ values.eksCluster }}
    backstage.io/kubernetes-label-selector: 'entity-id=${{ values.projectName }}'
    backstage.io/kubernetes-namespace: ${{ values.projectName }}
  links:
    - url: https://github.com/${{ values.owner }}/${{ values.repo }}
      title: 저장소
      icon: github
    - url: https://github.com/${{ values.owner }}/${{ values.repo }}/actions
      title: GitHub Actions
      icon: github
spec:
  type: service
  owner: platform-team
  lifecycle: experimental
