apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: elasticache
    sesac.io/template-color: "#DC2626"
    sesac.io/template-stack: ElastiCache
  name: terraform-elasticache
  title: ElastiCache Redis 생성
  description: 클러스터 모드, Multi-AZ, TLS/AUTH, 스냅샷, CloudWatch 알람 옵션을 포함한 ElastiCache Redis 클러스터를 생성합니다
  tags:
    - terraform
    - aws
    - elasticache
    - redis
    - cache
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: 기본 설정
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: ElastiCache 클러스터 이름 (소문자, 하이픈만 사용)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP

    - title: Redis 설정
      properties:
        clusterMode:
          type: string
          title: 클러스터 모드
          default: disabled
          enum:
            - disabled
            - enabled
          enumNames:
            - '클러스터 모드 비활성화 (단일 샤드, 최대 5개 복제본)'
            - '클러스터 모드 활성화 (다중 샤드, 수평 확장)'
        engineVersion:
          type: string
          title: Redis 엔진 버전
          default: '7.0'
          enum:
            - '7.1'
            - '7.0'
            - '6.2'
          enumNames:
            - 'Redis 7.1'
            - 'Redis 7.0'
            - 'Redis 6.2'
        nodeType:
          type: string
          title: 노드 유형
          default: cache.t3.micro
          enum:
            - cache.t3.micro
            - cache.t3.small
            - cache.t3.medium
            - cache.r7g.large
            - cache.r7g.xlarge
          enumNames:
            - 'cache.t3.micro (2 vCPU, 0.5 GB) - 개발/테스트'
            - 'cache.t3.small (2 vCPU, 1.37 GB)'
            - 'cache.t3.medium (2 vCPU, 3.09 GB)'
            - 'cache.r7g.large (2 vCPU, 13.07 GB) - 프로덕션'
            - 'cache.r7g.xlarge (4 vCPU, 26.32 GB) - 프로덕션'
        numCacheClusters:
          type: integer
          title: 캐시 노드 수 (클러스터 모드 비활성화)
          default: 1
          enum: [1, 2, 3]
          enumNames:
            - '1개 노드 (복제 없음)'
            - '2개 노드 (프라이머리 1개 + 복제본 1개)'
            - '3개 노드 (프라이머리 1개 + 복제본 2개)'
        numShards:
          type: integer
          title: 샤드 수 (클러스터 모드 활성화)
          default: 2
          enum: [2, 3, 4, 6]
          enumNames:
            - '2개 샤드'
            - '3개 샤드'
            - '4개 샤드'
            - '6개 샤드'
        replicasPerShard:
          type: integer
          title: 샤드당 복제본 수 (클러스터 모드 활성화)
          default: 1
          enum: [1, 2]
          enumNames:
            - '샤드당 1개 복제본'
            - '샤드당 2개 복제본'
        autoFailover:
          type: boolean
          title: 자동 장애 조치 활성화
          default: false
          description: 복제본이 최소 1개 필요합니다. 프라이머리 장애 발생 시 복제본을 자동으로 승격합니다.
        multiAz:
          type: boolean
          title: Multi-AZ 활성화
          default: false
          description: 여러 가용 영역에 걸쳐 복제본을 분산합니다 (자동 장애 조치 필요).
        transitEncryption:
          type: boolean
          title: TLS 활성화 (전송 중 암호화)
          default: true
          description: 클라이언트와 Redis 간의 전송 데이터를 암호화합니다
        atRestEncryption:
          type: boolean
          title: 저장 데이터 암호화 활성화
          default: true
        authEnabled:
          type: boolean
          title: AUTH 토큰 활성화
          default: false
          description: 클라이언트가 비밀번호로 인증하도록 요구합니다 (TLS 필요)
        snapshotRetentionDays:
          type: integer
          title: 스냅샷 보존 기간 (일)
          default: 1
          enum: [0, 1, 7, 14]
          enumNames:
            - '비활성화'
            - '1일'
            - '7일'
            - '14일'
        cloudwatchAlarms:
          type: boolean
          title: CloudWatch 알람 활성화
          default: false
          description: CPU 및 메모리 알람을 생성합니다 (GitHub 시크릿에 기존 SNS 토픽 ARN 필요)
        vpcNameFilter:
          type: string
          title: VPC Name 태그
          default: 'eksctl-sesac-ref-impl-cluster/VPC'
          description: 'ElastiCache를 배포할 VPC의 Name 태그. 최소 2개의 가용 영역에 걸친 프라이빗 서브넷이 있어야 합니다.'
        region:
          type: string
          title: AWS 리전
          default: ap-northeast-2
          enum:
            - us-east-1
            - us-west-2
            - ap-northeast-2
            - eu-west-1
          enumNames:
            - '미국 동부 (버지니아 북부)'
            - '미국 서부 (오리건)'
            - '아시아 태평양 (서울)'
            - '유럽 (아일랜드)'

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'ElastiCache Redis "${{ parameters.name }}" managed by Terraform'
        topics:
          - terraform
          - aws
          - elasticache
          - redis
          - backstage

    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          clusterMode: ${{ parameters.clusterMode }}
          engineVersion: ${{ parameters.engineVersion }}
          nodeType: ${{ parameters.nodeType }}
          numCacheClusters: ${{ parameters.numCacheClusters }}
          numShards: ${{ parameters.numShards }}
          replicasPerShard: ${{ parameters.replicasPerShard }}
          autoFailover: ${{ parameters.autoFailover }}
          multiAz: ${{ parameters.multiAz }}
          transitEncryption: ${{ parameters.transitEncryption }}
          atRestEncryption: ${{ parameters.atRestEncryption }}
          authEnabled: ${{ parameters.authEnabled }}
          snapshotRetentionDays: ${{ parameters.snapshotRetentionDays }}
          cloudwatchAlarms: ${{ parameters.cloudwatchAlarms }}
          vpcNameFilter: ${{ parameters.vpcNameFilter }}
          region: ${{ parameters.region }}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: register
      name: 카탈로그 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: 카탈로그에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
