apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: eks
    sesac.io/template-color: "#0EA5E9"
    sesac.io/template-stack: EKS
  name: terraform-eks
  title: Terraform으로 EKS 클러스터 생성
  description: VPC (퍼블릭/프라이빗 서브넷, NAT GW), 관리형 노드 그룹, 핵심 애드온 (EBS CSI, VPC CNI, CoreDNS, kube-proxy), AWS Load Balancer Controller 및 Fluent Bit용 IRSA 역할을 포함한 EKS 클러스터를 생성합니다
  tags:
    - terraform
    - aws
    - eks
    - kubernetes
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: 기본 설정
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: EKS 클러스터 이름
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP

    - title: 클러스터 설정
      properties:
        region:
          type: string
          title: AWS 리전
          default: ap-northeast-2
          enum:
            - us-east-1
            - us-west-2
            - ap-northeast-2
            - eu-west-1
          enumNames:
            - '미국 동부 (버지니아 북부)'
            - '미국 서부 (오리건)'
            - '아시아 태평양 (서울)'
            - '유럽 (아일랜드)'
        clusterVersion:
          type: string
          title: Kubernetes 버전
          default: '1.34'
          enum:
            - '1.34'
            - '1.33'
            - '1.32'
          enumNames:
            - 'Kubernetes 1.34 (최신)'
            - 'Kubernetes 1.33'
            - 'Kubernetes 1.32'
        environment:
          type: string
          title: 환경
          default: dev
          enum:
            - dev
            - staging
            - prod
          enumNames:
            - '개발'
            - '스테이징'
            - '프로덕션'
        vpcCidr:
          type: string
          title: VPC CIDR 블록
          default: '10.0.0.0/16'
          description: VPC의 CIDR 블록 (유효한 네트워크 주소여야 합니다). 가용 영역에 걸쳐 퍼블릭 3개, 프라이빗 3개의 서브넷이 생성됩니다.
          enum:
            - '10.0.0.0/16'
            - '10.1.0.0/16'
            - '10.2.0.0/16'
            - '10.10.0.0/16'
            - '172.16.0.0/16'
            - '192.168.0.0/16'
          enumNames:
            - '10.0.0.0/16'
            - '10.1.0.0/16'
            - '10.2.0.0/16'
            - '10.10.0.0/16'
            - '172.16.0.0/16'
            - '192.168.0.0/16'

    - title: 노드 그룹 설정
      properties:
        nodeInstanceType:
          type: string
          title: 노드 인스턴스 유형
          default: m5.large
          enum:
            - t3.medium
            - t3.large
            - m5.large
            - m5.xlarge
            - m5.2xlarge
            - c5.large
            - c5.xlarge
          enumNames:
            - 't3.medium (2 vCPU, 4 GB) - 개발/테스트'
            - 't3.large (2 vCPU, 8 GB)'
            - 'm5.large (2 vCPU, 8 GB) - 권장'
            - 'm5.xlarge (4 vCPU, 16 GB)'
            - 'm5.2xlarge (8 vCPU, 32 GB)'
            - 'c5.large (2 vCPU, 4 GB) - 컴퓨팅 최적화'
            - 'c5.xlarge (4 vCPU, 8 GB) - 컴퓨팅 최적화'
        nodeDesiredSize:
          type: integer
          title: 원하는 노드 수
          default: 3
          enum: [2, 3, 4, 5, 6]
          enumNames:
            - '2개 노드'
            - '3개 노드'
            - '4개 노드'
            - '5개 노드'
            - '6개 노드'
        nodeMinSize:
          type: integer
          title: 최소 노드 수
          default: 2
          enum: [1, 2, 3]
          enumNames:
            - '1개 노드'
            - '2개 노드'
            - '3개 노드'
        nodeMaxSize:
          type: integer
          title: 최대 노드 수
          default: 5
          enum: [3, 4, 5, 6, 8, 10]
          enumNames:
            - '3개 노드'
            - '4개 노드'
            - '5개 노드'
            - '6개 노드'
            - '8개 노드'
            - '10개 노드'

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'EKS cluster "${{ parameters.name }}" managed by Terraform'
        repoVisibility: public
        topics:
          - terraform
          - aws
          - eks
          - kubernetes
          - backstage

    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          region: ${{ parameters.region }}
          clusterVersion: ${{ parameters.clusterVersion }}
          environment: ${{ parameters.environment }}
          vpcCidr: ${{ parameters.vpcCidr }}
          nodeInstanceType: ${{ parameters.nodeInstanceType }}
          nodeDesiredSize: ${{ parameters.nodeDesiredSize }}
          nodeMinSize: ${{ parameters.nodeMinSize }}
          nodeMaxSize: ${{ parameters.nodeMaxSize }}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: register
      name: 카탈로그 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: 카탈로그에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
