apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: nodejs
    sesac.io/template-color: "#3C873A"
    sesac.io/template-stack: Node.js
  name: nodejs-nginx-webapp
  title: Node.js 웹 앱 (Nginx + 선택형 Express)
  description: Nginx로 서비스되는 Node.js 웹 프로젝트를 생성하며, 필요 시 Express 설정과 GitHub Actions CI를 함께 구성합니다.
  tags:
    - nodejs
    - nginx
    - express
    - web
spec:
  owner: platform-team
  type: service
  parameters:
    - title: 프로젝트 정보
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          title: 프로젝트 이름
          description: Kubernetes와 저장소 규칙에 맞는 프로젝트 이름
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          description: '레포지토리 이름(선택)을 비우면 프로젝트 이름(name)으로 자동 등록됩니다.'
          ui:field: RepoUrlFromProjectPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP
            sourceField: name
        repoVisibility:
          type: string
          title: 저장소 공개 범위
          description: GitHub 저장소를 public 또는 private 중에서 선택합니다.
          default: public
          enum:
            - public
            - private
    - title: 런타임 옵션
      properties:
        appLanguage:
          type: string
          title: 언어
          description: JavaScript 또는 TypeScript 프로젝트 스캐폴드를 선택합니다.
          default: javascript
          enum:
            - javascript
            - typescript
        nodeVersion:
          type: string
          title: Node.js Version
          description: 기본값은 24.13.1 LTS이며, 다른 버전을 선택할 수 있습니다.
          default: 24.13.1
          enum:
            - 24.13.1
            - 22.17.1
            - 20.19.4
        useExpress:
          type: boolean
          title: Express 설치
          description: 선택하면 Express 서버 스캐폴드와 의존성이 자동으로 추가됩니다.
          default: false
    - title: 네트워크 옵션
      properties:
        servicePort:
          type: number
          title: 서비스 포트
          description: 클러스터 내부에 노출할 서비스 포트입니다(Nginx target port는 80으로 고정).
          default: 80
        enableIngress:
          type: boolean
          title: Ingress 생성
          description: 선택하면 Ingress 매니페스트를 생성합니다.
          default: true
        hostPrefix:
          type: string
          title: 호스트 접두사
          description: '비우면 프로젝트 이름(name)을 자동으로 사용합니다. 예: `node-test`'
          pattern: '^[a-z0-9-]+$'
          ui:field: DefaultFromProjectText
          ui:options:
            sourceField: name
            helperText: 호스트 접두사를 비우면 프로젝트 이름(name)으로 자동 등록됩니다.
        baseDomain:
          type: string
          title: 기본 도메인
          description: Ingress 호스트를 구성할 때 사용할 기본 도메인
          default: already11.cloud
    - title: 클라우드/배포 옵션
      required:
        - eksCluster
      properties:
        eksCluster:
          type: string
          title: EKS Cluster
          description: 배포 대상 EKS 클러스터를 선택합니다. (필수)
          default: sesac-ref-impl
          ui:field: EksClusterPicker
          ui:options:
            region: ap-northeast-2
            hubClusterName: sesac-ref-impl
        acmCertificateSource:
          type: string
          title: ACM 인증서 선택 방식
          description: ALB(허브/비허브) HTTPS 인증서 입력 방식을 선택합니다.
          default: preset
          enum:
            - preset
            - custom
          enumNames:
            - 프리셋에서 선택(권장)
            - ARN 직접 입력
        targetNamespace:
          type: string
          title: 대상 Namespace
          description: 기본값은 프로젝트 이름(name)이며, 필요하면 수정할 수 있습니다.
          pattern: '^[a-z0-9-]+$'
          ui:field: DefaultFromProjectText
          ui:options:
            sourceField: name
            helperText: 대상 Namespace를 비우면 프로젝트 이름(name)으로 자동 등록됩니다.
        argoProject:
          type: string
          title: Argo CD Project
          description: 생성할 Application이 소속될 Argo CD Project를 선택합니다.
          default: default
          ui:field: ArgoProjectPicker
          ui:options:
            argoInstance: in-cluster
      dependencies:
        acmCertificateSource:
          oneOf:
            - properties:
                acmCertificateSource:
                  enum: [preset]
                acmCertificateArnPreset:
                  type: string
                  title: ACM Certificate ARN (프리셋)
                  description: ALB를 사용할 때는 앱 도메인과 일치하는 인증서를 선택하세요. (발급 상태 ISSUED만 노출)
                  ui:field: AcmCertificatePicker
                  ui:options:
                    region: ap-northeast-2
                    statuses:
                      - ISSUED
            - properties:
                acmCertificateSource:
                  enum: [custom]
                acmCertificateArn:
                  type: string
                  title: ACM Certificate ARN (직접 입력)
                  description: ALB를 사용할 때는 앱 도메인과 일치하는 인증서(SAN: *.already11.cloud 또는 FQDN) ARN을 입력하세요.

  steps:
    - id: preflight-argocd
      name: ArgoCD 사전 검증
      action: cnoe:create-argocd-app
      input:
        preflightOnly: true
        appName: ${{ parameters.name }}
        appNamespace: ${{ parameters.targetNamespace || parameters.name }}
        argoInstance: in-cluster
        projectName: ${{ parameters.argoProject }}
        destinationEksClusterName: ${{ parameters.eksCluster }}
        destinationEksClusterRegion: ap-northeast-2
        hubClusterName: sesac-ref-impl
        repoUrl: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/gitops
        path: apps/${{ parameters.name }}

    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.repoVisibility }}
        allowAutoMerge: true
        allowSquashMerge: true
        deleteBranchOnMerge: true
        description: Backstage 템플릿으로 생성된 Node.js Nginx 웹 프로젝트
        topics:
          - backstage
          - nodejs
          - nginx
          - webapp

    - id: template-base
      name: 기본 프로젝트 생성
      action: fetch:template
      input:
        url: ./skeleton-base
        values:
          name: ${{ parameters.name }}
          appLanguage: ${{ parameters.appLanguage }}
          nodeVersion: ${{ parameters.nodeVersion }}
          useExpress: ${{ parameters.useExpress }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}
          eksCluster: ${{ parameters.eksCluster }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          gitopsOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          gitopsRepo: gitops
          acmCertificateArn: ${{ parameters.acmCertificateArn || parameters.acmCertificateArnPreset }}

    - id: template-ingress
      if: ${{ parameters.enableIngress }}
      name: Ingress 매니페스트 추가
      action: fetch:template
      input:
        url: ./skeleton-ingress
        values:
          name: ${{ parameters.name }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}

    - id: template-express
      if: ${{ parameters.useExpress && parameters.appLanguage == 'javascript' }}
      name: Express 오버레이 추가 (JavaScript)
      action: fetch:template
      input:
        url: ./skeleton-express
        values:
          name: ${{ parameters.name }}
          nodeVersion: ${{ parameters.nodeVersion }}

    - id: template-typescript
      if: ${{ parameters.appLanguage == 'typescript' }}
      name: TypeScript 오버레이 추가
      action: fetch:template
      input:
        url: ./skeleton-typescript-base
        values:
          name: ${{ parameters.name }}
          nodeVersion: ${{ parameters.nodeVersion }}

    - id: template-express-typescript
      if: ${{ parameters.useExpress && parameters.appLanguage == 'typescript' }}
      name: Express 오버레이 추가 (TypeScript)
      action: fetch:template
      input:
        url: ./skeleton-typescript-express
        values:
          name: ${{ parameters.name }}
          nodeVersion: ${{ parameters.nodeVersion }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: roadiehq:utils:sleep
      input:
        amount: 5

    - id: register
      name: Catalog 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: create-argocd-app
      name: ArgoCD App 생성
      action: cnoe:create-argocd-app
      input:
        appName: ${{ parameters.name }}
        appNamespace: ${{ parameters.targetNamespace || parameters.name }}
        argoInstance: in-cluster
        projectName: ${{ parameters.argoProject }}
        destinationEksClusterName: ${{ parameters.eksCluster }}
        destinationEksClusterRegion: ap-northeast-2
        hubClusterName: sesac-ref-impl
        repoUrl: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/gitops
        path: apps/${{ parameters.name }}
        cleanupOnFailure: true
        cleanupGithubOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
        cleanupGithubRepo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        cleanupEcrRepository: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

  output:
    links:
      - title: Catalog에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
