apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: rds
    sesac.io/template-color: "#2563EB"
    sesac.io/template-stack: RDS
  name: terraform-rds
  title: Terraform으로 RDS 데이터베이스 생성
  description: Multi-AZ, Performance Insights, CloudWatch Logs, Secrets Manager 연동을 포함한 RDS 인스턴스 (PostgreSQL/MySQL/Aurora)를 생성합니다
  tags:
    - terraform
    - aws
    - rds
    - database
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: 기본 설정
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: RDS 인스턴스 이름 (소문자, 하이픈만 사용)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP
    - title: RDS 설정
      properties:
        engine:
          type: string
          title: 데이터베이스 엔진
          default: postgres
          enum:
            - postgres
            - mysql
            - aurora-postgresql
            - aurora-mysql
          enumNames:
            - 'PostgreSQL 15'
            - 'MySQL 8.0'
            - 'Aurora PostgreSQL 15'
            - 'Aurora MySQL 8.0'
        instanceClass:
          type: string
          title: 인스턴스 클래스
          default: db.t3.micro
          enum:
            - db.t3.micro
            - db.t3.small
            - db.t3.medium
            - db.r6g.large
          enumNames:
            - 'db.t3.micro (2 vCPU, 1 GB) - 개발/테스트'
            - 'db.t3.small (2 vCPU, 2 GB)'
            - 'db.t3.medium (2 vCPU, 4 GB)'
            - 'db.r6g.large (2 vCPU, 16 GB) - 프로덕션'
        multiAz:
          type: boolean
          title: Multi-AZ 배포
          default: false
          description: 다른 가용 영역에 대기 복제본을 활성화합니다
        backupRetentionDays:
          type: integer
          title: 백업 보존 기간 (일)
          default: 7
          enum: [7, 14, 30]
          enumNames:
            - '7일'
            - '14일'
            - '30일'
        performanceInsights:
          type: boolean
          title: Performance Insights 활성화
          default: false
          description: db.t3.micro에서는 지원되지 않습니다
        cloudwatchLogs:
          type: boolean
          title: CloudWatch로 로그 내보내기
          default: true
        secretsManager:
          type: boolean
          title: Secrets Manager에 자격 증명 저장
          default: true
          description: DB 비밀번호를 자동 생성하고 연결 정보를 저장합니다
        vpcNameFilter:
          type: string
          title: VPC Name 태그
          default: 'eksctl-sesac-ref-impl-cluster/VPC'
          description: 'RDS를 배포할 VPC의 Name 태그. 최소 2개의 가용 영역에 걸친 프라이빗 서브넷이 있어야 합니다. (예: eksctl-my-cluster/VPC)'
        region:
          type: string
          title: AWS 리전
          default: ap-northeast-2
          enum:
            - us-east-1
            - us-west-2
            - ap-northeast-2
            - eu-west-1
          enumNames:
            - '미국 동부 (버지니아 북부)'
            - '미국 서부 (오리건)'
            - '아시아 태평양 (서울)'
            - '유럽 (아일랜드)'
  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'RDS "${{ parameters.name }}" (${{ parameters.engine }}) managed by Terraform'
        topics:
          - terraform
          - aws
          - rds
          - database
          - backstage
    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          engine: ${{ parameters.engine }}
          instanceClass: ${{ parameters.instanceClass }}
          multiAz: ${{ parameters.multiAz }}
          backupRetentionDays: ${{ parameters.backupRetentionDays }}
          performanceInsights: ${{ parameters.performanceInsights }}
          cloudwatchLogs: ${{ parameters.cloudwatchLogs }}
          secretsManager: ${{ parameters.secretsManager }}
          vpcNameFilter: ${{ parameters.vpcNameFilter }}
          region: ${{ parameters.region }}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5
    - id: register
      name: 카탈로그 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: 카탈로그에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
