apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: ec2
    sesac.io/template-color: "#F59E0B"
    sesac.io/template-stack: EC2
  name: terraform-ec2
  title: Terraform으로 EC2 인스턴스 생성
  description: Terraform과 GitHub Actions를 사용하여 EC2 인스턴스를 생성합니다
  tags:
    - terraform
    - aws
    - ec2
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: 기본 설정
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: EC2 인스턴스 이름
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          description: '중요: 개인 계정이 아닌 GitHub 조직 이름을 사용하세요 (예: SAMJOYAP). GitHub Apps는 조직에서만 동작합니다.'
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP  # Update this to your GitHub Organization name after forking

    - title: EC2 설정
      properties:
        instanceType:
          type: string
          title: 인스턴스 유형
          description: EC2 인스턴스 유형
          default: t3.micro
          enum:
            - t3.micro
            - t3.small
            - t3.medium
          enumNames:
            - 't3.micro (2 vCPU, 1 GB RAM) - 프리 티어'
            - 't3.small (2 vCPU, 2 GB RAM)'
            - 't3.medium (2 vCPU, 4 GB RAM)'
        region:
          type: string
          title: AWS 리전
          description: 배포할 AWS 리전
          default: ap-northeast-2
          enum:
            - us-east-1
            - us-west-2
            - ap-northeast-2
            - eu-west-1
          enumNames:
            - '미국 동부 (버지니아 북부)'
            - '미국 서부 (오리건)'
            - '아시아 태평양 (서울)'
            - '유럽 (아일랜드)'
        vpcName:
          type: string
          title: VPC 이름
          description: '배포할 VPC의 Name 태그 (예: eksctl-sesac-ref-impl-cluster/VPC). AWS 콘솔 → VPC → 내 VPC → Name 열에서 확인하세요.'

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'EC2 instance "${{ parameters.name }}" managed by Terraform'
        repoVisibility: public
        topics:
          - terraform
          - aws
          - ec2
          - backstage

    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          instanceType: ${{ parameters.instanceType }}
          region: ${{ parameters.region }}
          vpcName: ${{ parameters.vpcName }}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: register
      name: 카탈로그 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: 카탈로그에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
