apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates a Basic Kubernetes Deployment
  name: basic
  title: Create a Basic Deployment
spec:
  owner: guests
  type: service
  parameters:
    - title: Configuration Options
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: name of this application
          ui:autofocus: true
        repoUrl:
          title: Repository Location
          type: string
          description: 'IMPORTANT: Use your GitHub Organization name (e.g., SAMJOYAP), not personal account. GitHub Apps only work with Organizations.'
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP  # Update this to your GitHub Organization name after forking

  steps:
    - id: create-repo
      name: Create Repository
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: This is an example app

    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}

    - id: init-repo
      name: Initialize Repository
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: Waiting for the repo to be ready
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.name}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: ${{ steps['create-repo'].output.remoteUrl }}
        path: "manifests"

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'

  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
