apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: java
    sesac.io/template-color: "#EA6A47"
    sesac.io/template-stack: Java
  name: springboot-gradle-apache
  title: Java 웹 앱 (Apache + Spring Boot)
  description: Apache로 서비스되는 Java 웹 프로젝트를 생성하며, Spring Boot 설정과 선택형 Ingress를 함께 구성합니다.
  tags:
    - java
    - spring-boot
    - maven
    - gradle
    - apache
spec:
  owner: platform-team
  type: service
  parameters:
    - title: 프로젝트 정보
      required:
        - projectName
        - repoUrl
      properties:
        projectName:
          type: string
          title: 프로젝트 이름
          description: Kubernetes 규칙에 맞는 프로젝트 이름
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          description: '레포지토리 이름(선택)을 비우면 프로젝트 이름(projectName)으로 자동 등록됩니다.'
          ui:field: RepoUrlFromProjectPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP
            sourceField: projectName
        repoVisibility:
          type: string
          title: 저장소 공개 범위
          description: GitHub 저장소를 public 또는 private 중에서 선택합니다.
          default: public
          enum:
            - public
            - private
        groupId:
          type: string
          title: Group ID
          description: 'Java 패키지 기준이 되는 groupId입니다. (예: com.example)'
          default: com.example
        artifactId:
          type: string
          title: Artifact ID
          description: 빌드 산출물 이름으로 사용할 artifactId입니다.
          default: app
    - title: 버전 및 빌드 옵션
      properties:
        buildTool:
          type: string
          title: Build Tool
          description: 프로젝트 빌드 도구를 선택합니다.
          default: maven
          enum:
            - maven
            - gradle
          enumNames:
            - Maven
            - Gradle
          ui:widget: radio
        javaVersion:
          type: string
          title: Java Version
          description: 프로젝트 빌드와 실행에 사용할 Java 버전을 선택합니다.
          default: '21'
          enum:
            - '17'
            - '21'
            - '24'
        springBootVersion:
          type: string
          title: Spring Boot Version
          description: 애플리케이션 프레임워크로 사용할 Spring Boot 버전입니다.
          default: 3.4.10
          enum:
            - 3.2.12
            - 3.3.6
            - 3.4.10
        packaging:
          type: string
          title: 패키징 방식
          description: 배포 산출물 패키징 형식을 선택합니다.
          default: jar
        useActuator:
          type: boolean
          title: Spring Actuator 사용
          description: 선택하면 상태 확인 및 메트릭 엔드포인트를 포함합니다.
          default: true
        useSpringWeb:
          type: boolean
          title: Spring Web 사용
          description: 선택하면 REST API/웹 기능을 위한 Spring Web 의존성을 추가합니다.
          default: true
        useLombok:
          type: boolean
          title: Lombok 사용
          description: 선택하면 Lombok 의존성을 추가해 보일러플레이트 코드를 줄입니다.
          default: false
      ui:order:
        - buildTool
        - gradleVersion
        - javaVersion
        - springBootVersion
        - packaging
        - useActuator
        - useSpringWeb
        - useLombok
      dependencies:
        buildTool:
          oneOf:
            - properties:
                buildTool:
                  enum: [maven]
                packaging:
                  type: string
                  title: 패키징 방식
                  default: jar
                  enum:
                    - jar
            - properties:
                buildTool:
                  enum: [gradle]
                packaging:
                  type: string
                  title: 패키징 방식
                  default: jar
                  enum:
                    - jar
                    - war
                gradleVersion:
                  type: string
                  title: Gradle Version
                  description: 프로젝트 빌드에 사용할 Gradle 버전입니다.
                  default: '8.10.2'
                  enum:
                    - '8.8'
                    - '8.10.2'
                    - '8.12.1'
    - title: 네트워크 옵션
      properties:
        servicePort:
          type: number
          title: 서비스 포트
          description: 클러스터 내부에서 서비스가 수신할 포트입니다.
          default: 80
        enableIngress:
          type: boolean
          title: Ingress 생성
          description: 선택하면 외부 접근을 위한 Ingress 매니페스트를 생성합니다.
          default: true
        hostPrefix:
          type: string
          title: 호스트 접두사
          description: '비우면 프로젝트 이름(projectName)을 자동으로 사용합니다. 예: `java-test`'
          pattern: '^[a-z0-9-]+$'
          ui:field: DefaultFromProjectText
          ui:options:
            sourceField: projectName
            helperText: 호스트 접두사를 비우면 프로젝트 이름(projectName)으로 자동 등록됩니다.
        baseDomain:
          type: string
          title: 기본 도메인
          description: Ingress 호스트를 구성할 때 사용할 기본 도메인입니다.
          default: sesac.already11.cloud
    - title: 클라우드/배포 옵션
      required:
        - eksCluster
      properties:
        eksCluster:
          type: string
          title: EKS Cluster
          description: 배포 대상 EKS 클러스터를 선택합니다. (필수)
          default: sesac-ref-impl
          ui:field: EksClusterPicker
          ui:options:
            region: ap-northeast-2
            hubClusterName: sesac-ref-impl
        acmCertificateArn:
          type: string
          title: ACM Certificate ARN (비허브 HTTPS)
          description: 비허브(ALB) 클러스터에 배포할 때 사용할 ACM 인증서 ARN입니다. 허브 클러스터(nginx+cert-manager) 배포 시에는 비워둘 수 있습니다.
        targetNamespace:
          type: string
          title: 대상 Namespace
          description: 기본값은 프로젝트 이름(projectName)이며, 필요하면 수정할 수 있습니다.
          pattern: '^[a-z0-9-]+$'
          ui:field: DefaultFromProjectText
          ui:options:
            sourceField: projectName
            helperText: 대상 Namespace를 비우면 프로젝트 이름(projectName)으로 자동 등록됩니다.
        argoProject:
          type: string
          title: Argo CD Project
          description: 생성할 Application이 소속될 Argo CD Project를 선택합니다.
          default: default
          ui:field: ArgoProjectPicker
          ui:options:
            argoInstance: in-cluster

  steps:
    - id: preflight-argocd
      name: ArgoCD 사전 검증
      action: cnoe:create-argocd-app
      input:
        preflightOnly: true
        appName: ${{ parameters.projectName }}
        appNamespace: ${{ parameters.targetNamespace || parameters.projectName }}
        argoInstance: in-cluster
        projectName: ${{ parameters.argoProject }}
        destinationEksClusterName: ${{ parameters.eksCluster }}
        destinationEksClusterRegion: ap-northeast-2
        hubClusterName: sesac-ref-impl
        repoUrl: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/gitops
        path: apps/${{ parameters.projectName }}

    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.repoVisibility }}
        allowAutoMerge: true
        allowSquashMerge: true
        deleteBranchOnMerge: true
        description: Backstage 템플릿으로 생성된 Java 웹 프로젝트 (Apache + Spring Boot + ${{ parameters.buildTool | upper }})
        topics:
          - spring-boot
          - ${{ parameters.buildTool }}
          - java
          - apache
          - backstage

    - id: template-base
      name: 기본 프로젝트 생성
      action: fetch:template
      input:
        url: ./skeleton-base
        values:
          projectName: ${{ parameters.projectName }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          buildTool: ${{ parameters.buildTool }}
          gradleVersion: ${{ parameters.gradleVersion }}
          packaging: ${{ parameters.packaging }}
          useActuator: ${{ parameters.useActuator }}
          useSpringWeb: ${{ parameters.useSpringWeb }}
          useLombok: ${{ parameters.useLombok }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}
          eksCluster: ${{ parameters.eksCluster }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          gitopsOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          gitopsRepo: gitops
          acmCertificateArn: ${{ parameters.acmCertificateArn }}

    - id: template-gradle-overlay
      if: ${{ parameters.buildTool == 'gradle' }}
      name: 빌드 도구 오버레이 적용
      action: fetch:template
      input:
        url: ./skeleton-gradle
        replace: true
        values:
          projectName: ${{ parameters.projectName }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          buildTool: ${{ parameters.buildTool }}
          gradleVersion: ${{ parameters.gradleVersion }}
          packaging: ${{ parameters.packaging }}
          useActuator: ${{ parameters.useActuator }}
          useSpringWeb: ${{ parameters.useSpringWeb }}
          useLombok: ${{ parameters.useLombok }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}
          eksCluster: ${{ parameters.eksCluster }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          gitopsOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          gitopsRepo: gitops
          acmCertificateArn: ${{ parameters.acmCertificateArn }}

    - id: template-maven-overlay
      if: ${{ parameters.buildTool == 'maven' }}
      name: Maven/DevSecOps 오버레이 적용
      action: fetch:template
      input:
        url: ./skeleton-maven
        replace: true
        values:
          projectName: ${{ parameters.projectName }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          buildTool: ${{ parameters.buildTool }}
          packaging: ${{ parameters.packaging }}
          useActuator: ${{ parameters.useActuator }}
          useSpringWeb: ${{ parameters.useSpringWeb }}
          useLombok: ${{ parameters.useLombok }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}
          eksCluster: ${{ parameters.eksCluster }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          gitopsOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          gitopsRepo: gitops
          acmCertificateArn: ${{ parameters.acmCertificateArn }}

    - id: template-ingress
      if: ${{ parameters.enableIngress }}
      name: Ingress 매니페스트 추가
      action: fetch:template
      input:
        url: ./skeleton-ingress
        values:
          projectName: ${{ parameters.projectName }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: roadiehq:utils:sleep
      input:
        amount: 5

    - id: register
      name: Catalog 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
        optional: true

    - id: create-argocd-app
      name: ArgoCD App 생성
      action: cnoe:create-argocd-app
      input:
        appName: ${{ parameters.projectName }}
        appNamespace: ${{ parameters.targetNamespace || parameters.projectName }}
        argoInstance: in-cluster
        projectName: ${{ parameters.argoProject }}
        destinationEksClusterName: ${{ parameters.eksCluster }}
        destinationEksClusterRegion: ap-northeast-2
        hubClusterName: sesac-ref-impl
        repoUrl: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/gitops
        path: apps/${{ parameters.projectName }}
        cleanupOnFailure: true
        cleanupGithubOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
        cleanupGithubRepo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        cleanupEcrRepository: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

  output:
    links:
      - title: Catalog에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
      - title: GitHub Actions 보기
        icon: github
        url: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}/actions
