apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-gradle-apache
  title: Java 웹 앱 (Apache + Spring Boot + Gradle)
  description: Apache로 서비스되는 Java 웹 프로젝트를 생성하며, Spring Boot + Gradle 설정과 선택형 Ingress를 함께 구성합니다.
  tags:
    - java
    - spring-boot
    - gradle
    - apache
spec:
  owner: platform-team
  type: service
  parameters:
    - title: 프로젝트 정보
      required:
        - projectName
        - repoUrl
      properties:
        projectName:
          type: string
          title: 프로젝트 이름
          description: Kubernetes 규칙에 맞는 프로젝트 이름
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          description: '중요: 개인 계정이 아닌 GitHub Organization 이름(예: SAMJOYAP)을 사용하세요.'
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP
        repoVisibility:
          type: string
          title: 저장소 공개 범위
          description: GitHub 저장소를 public 또는 private 중에서 선택합니다.
          default: public
          enum:
            - public
            - private
        groupId:
          type: string
          title: Group ID
          description: Java 패키지 기준이 되는 groupId입니다. (예: com.example)
          default: com.example
        artifactId:
          type: string
          title: Artifact ID
          description: 빌드 산출물 이름으로 사용할 artifactId입니다.
          default: app
    - title: 버전 및 빌드 옵션
      properties:
        javaVersion:
          type: string
          title: Java Version
          description: 프로젝트 빌드와 실행에 사용할 Java 버전을 선택합니다.
          default: '21'
          enum:
            - '17'
            - '21'
            - '24'
        springBootVersion:
          type: string
          title: Spring Boot Version
          description: 애플리케이션 프레임워크로 사용할 Spring Boot 버전입니다.
          default: 3.4.5
          enum:
            - 3.2.12
            - 3.3.6
            - 3.4.5
        gradleVersion:
          type: string
          title: Gradle Version
          description: 프로젝트 빌드에 사용할 Gradle 버전입니다.
          default: '8.10.2'
          enum:
            - '8.8'
            - '8.10.2'
            - '8.12.1'
        packaging:
          type: string
          title: 패키징 방식
          description: 배포 산출물 패키징 형식을 선택합니다.
          default: jar
          enum:
            - jar
            - war
        useActuator:
          type: boolean
          title: Spring Actuator 사용
          description: 선택하면 상태 확인 및 메트릭 엔드포인트를 포함합니다.
          default: true
        useSpringWeb:
          type: boolean
          title: Spring Web 사용
          description: 선택하면 REST API/웹 기능을 위한 Spring Web 의존성을 추가합니다.
          default: true
        useLombok:
          type: boolean
          title: Lombok 사용
          description: 선택하면 Lombok 의존성을 추가해 보일러플레이트 코드를 줄입니다.
          default: false
    - title: 네트워크 옵션
      required:
        - hostPrefix
      properties:
        servicePort:
          type: number
          title: 서비스 포트
          description: 클러스터 내부에서 서비스가 수신할 포트입니다.
          default: 80
        enableIngress:
          type: boolean
          title: Ingress 생성
          description: 선택하면 외부 접근을 위한 Ingress 매니페스트를 생성합니다.
          default: true
        hostPrefix:
          type: string
          title: 호스트 접두사
          description: 서브도메인 접두사입니다. 예: `java-test`
          pattern: '^[a-z0-9-]+$'
        baseDomain:
          type: string
          title: 기본 도메인
          description: Ingress 호스트를 구성할 때 사용할 기본 도메인입니다.
          default: sesac.already11.cloud
    - title: 클라우드 배포 옵션
      properties:
        eksCluster:
          type: string
          title: EKS Cluster
          description: 배포 대상 EKS 클러스터를 선택합니다. (향후 VPC/서브넷 선택 항목 확장 예정)
          ui:field: EksClusterPicker
          ui:options:
            region: ap-northeast-2
    - title: 배포 옵션
      properties:
        targetNamespace:
          type: string
          title: 대상 Namespace
          description: 비워두면 프로젝트 이름(projectName)을 Namespace로 사용합니다.
          pattern: '^[a-z0-9-]+$'
        argoProject:
          type: string
          title: Argo CD Project
          description: Argo CD에 생성할 Application의 Project 이름입니다.
          default: default
          ui:field: ArgoProjectPicker
          ui:options:
            argoInstance: in-cluster

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.repoVisibility }}
        allowAutoMerge: true
        allowSquashMerge: true
        deleteBranchOnMerge: true
        description: Backstage 템플릿으로 생성된 Java 웹 프로젝트 (Apache + Spring Boot + Gradle)
        topics:
          - spring-boot
          - gradle
          - java
          - apache
          - backstage

    - id: template-base
      name: 기본 프로젝트 생성
      action: fetch:template
      input:
        url: ./skeleton-base
        values:
          projectName: ${{ parameters.projectName }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          gradleVersion: ${{ parameters.gradleVersion }}
          packaging: ${{ parameters.packaging }}
          useActuator: ${{ parameters.useActuator }}
          useSpringWeb: ${{ parameters.useSpringWeb }}
          useLombok: ${{ parameters.useLombok }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}
          eksCluster: ${{ parameters.eksCluster }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          gitopsOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          gitopsRepo: gitops

    - id: template-ingress
      if: ${{ parameters.enableIngress }}
      name: Ingress 매니페스트 추가
      action: fetch:template
      input:
        url: ./skeleton-ingress
        values:
          projectName: ${{ parameters.projectName }}
          servicePort: ${{ parameters.servicePort }}
          hostPrefix: ${{ parameters.hostPrefix }}
          baseDomain: ${{ parameters.baseDomain }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: roadiehq:utils:sleep
      input:
        amount: 5

    - id: register
      name: Catalog 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: create-argocd-app
      name: ArgoCD App 생성
      action: cnoe:create-argocd-app
      input:
        appName: ${{ parameters.projectName }}
        appNamespace: ${{ parameters.targetNamespace || parameters.projectName }}
        argoInstance: in-cluster
        projectName: ${{ parameters.argoProject }}
        destinationEksClusterName: ${{ parameters.eksCluster }}
        destinationEksClusterRegion: ap-northeast-2
        repoUrl: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/gitops
        path: apps/${{ parameters.projectName }}
        cleanupOnFailure: true
        cleanupGithubOwner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
        cleanupGithubRepo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        cleanupEcrRepository: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

  output:
    links:
      - title: Catalog에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
