apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    sesac.io/template-icon: datapipeline
    sesac.io/template-color: "#0D9488"
    sesac.io/template-stack: Data Pipeline
  name: terraform-data-pipeline
  title: 데이터 파이프라인 (Glue/EMR) 생성
  description: S3 Data Lake, Glue Catalog/Crawler/Job, 선택적 EMR Spark 클러스터, KMS 암호화, CloudWatch 로깅을 포함한 AWS 데이터 파이프라인을 생성합니다
  tags:
    - terraform
    - aws
    - glue
    - emr
    - data-pipeline
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: 기본 설정
      required:
        - name
        - repoUrl
      properties:
        name:
          type: string
          description: 데이터 파이프라인 이름 (소문자, 하이픈만 사용)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        repoUrl:
          title: 저장소 위치
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - SAMJOYAP

    - title: 파이프라인 유형
      properties:
        pipelineType:
          type: string
          title: 파이프라인 유형
          default: glue
          enum:
            - glue
            - emr
            - both
          enumNames:
            - 'Glue만 (S3 Data Lake + Glue Catalog + Crawler + Job)'
            - 'EMR만 (S3 Data Lake + EMR Spark 클러스터)'
            - 'Glue와 EMR 모두'

    - title: S3 Data Lake
      properties:
        s3BucketSuffix:
          type: string
          title: S3 버킷 이름 접미사
          description: 버킷 이름은 "{name}-datalake-{suffix}"로 지정됩니다. AWS 계정 ID 또는 고유한 문자열을 사용하세요.
          default: datalake
        s3Prefix:
          type: string
          title: 원시 데이터 S3 키 접두사
          default: raw/
          description: 원시 입력 데이터가 저장되는 S3 접두사 (Crawler에서 사용)

    - title: Glue 설정
      properties:
        glueJobType:
          type: string
          title: Glue 작업 유형
          default: glueetl
          enum:
            - glueetl
            - pythonshell
          enumNames:
            - 'Glue ETL (Apache Spark, 최소 2 DPU)'
            - 'Python Shell (0.0625 DPU, 경량 스크립트용)'
        glueWorkerType:
          type: string
          title: Glue 워커 유형 (ETL 전용)
          default: G.1X
          enum:
            - G.025X
            - G.1X
            - G.2X
          enumNames:
            - 'G.025X (0.25 DPU)'
            - 'G.1X (1 DPU, 4 vCPU, 16 GB)'
            - 'G.2X (2 DPU, 8 vCPU, 32 GB)'
        glueWorkerCount:
          type: integer
          title: Glue 워커 수
          default: 2
          enum: [2, 5, 10]
          enumNames:
            - '2개 워커'
            - '5개 워커'
            - '10개 워커'
        crawlerSchedule:
          type: string
          title: Crawler 스케줄 (cron)
          default: 'cron(0 1 * * ? *)'
          description: '자동 크롤링을 위한 cron 표현식. 수동으로만 실행하려면 "disabled"를 사용하세요.'

    - title: EMR 설정
      properties:
        emrReleaseLabel:
          type: string
          title: EMR 릴리스 레이블
          default: emr-7.0.0
          enum:
            - emr-7.0.0
            - emr-6.15.0
            - emr-6.14.0
          enumNames:
            - 'EMR 7.0.0 (Spark 3.5, Hadoop 3.3)'
            - 'EMR 6.15.0 (Spark 3.4, Hadoop 3.3)'
            - 'EMR 6.14.0 (Spark 3.4, Hadoop 3.3)'
        emrMasterInstanceType:
          type: string
          title: EMR 마스터 인스턴스 유형
          default: m5.xlarge
          enum:
            - m5.xlarge
            - m5.2xlarge
            - r5.xlarge
          enumNames:
            - 'm5.xlarge (4 vCPU, 16 GB)'
            - 'm5.2xlarge (8 vCPU, 32 GB)'
            - 'r5.xlarge (4 vCPU, 32 GB)'
        emrCoreInstanceType:
          type: string
          title: EMR 코어 인스턴스 유형
          default: m5.xlarge
          enum:
            - m5.xlarge
            - m5.2xlarge
            - r5.xlarge
          enumNames:
            - 'm5.xlarge (4 vCPU, 16 GB)'
            - 'm5.2xlarge (8 vCPU, 32 GB)'
            - 'r5.xlarge (4 vCPU, 32 GB)'
        emrCoreCount:
          type: integer
          title: EMR 코어 노드 수
          default: 2
          enum: [2, 4, 8]
          enumNames:
            - '2개 코어 노드'
            - '4개 코어 노드'
            - '8개 코어 노드'

    - title: 보안 및 로깅
      properties:
        kmsEncryption:
          type: boolean
          title: KMS 암호화 활성화
          default: false
          description: AWS 관리형 KMS 키로 S3 데이터, Glue 작업 북마크, EMR EBS 볼륨을 암호화합니다
        cloudwatchLogs:
          type: boolean
          title: CloudWatch로 로그 내보내기
          default: true
          description: Glue 작업 및 EMR 애플리케이션 로그를 CloudWatch Logs로 전송합니다
        region:
          type: string
          title: AWS 리전
          default: ap-northeast-2
          enum:
            - us-east-1
            - us-west-2
            - ap-northeast-2
            - eu-west-1
          enumNames:
            - '미국 동부 (버지니아 북부)'
            - '미국 서부 (오리건)'
            - '아시아 태평양 (서울)'
            - '유럽 (아일랜드)'

  steps:
    - id: create-repo
      name: 저장소 생성
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'Data Pipeline "${{ parameters.name }}" (${{ parameters.pipelineType }}) managed by Terraform'
        topics:
          - terraform
          - aws
          - glue
          - emr
          - data-pipeline
          - backstage

    - id: template
      name: 컴포넌트 생성
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          pipelineType: ${{ parameters.pipelineType }}
          s3BucketSuffix: ${{ parameters.s3BucketSuffix }}
          s3Prefix: ${{ parameters.s3Prefix }}
          glueJobType: ${{ parameters.glueJobType }}
          glueWorkerType: ${{ parameters.glueWorkerType }}
          glueWorkerCount: ${{ parameters.glueWorkerCount }}
          crawlerSchedule: ${{ parameters.crawlerSchedule }}
          emrReleaseLabel: ${{ parameters.emrReleaseLabel }}
          emrMasterInstanceType: ${{ parameters.emrMasterInstanceType }}
          emrCoreInstanceType: ${{ parameters.emrCoreInstanceType }}
          emrCoreCount: ${{ parameters.emrCoreCount }}
          kmsEncryption: ${{ parameters.kmsEncryption }}
          cloudwatchLogs: ${{ parameters.cloudwatchLogs }}
          region: ${{ parameters.region }}
          repoUrl: ${{ parameters.repoUrl }}
          remoteUrl: ${{ steps['create-repo'].output.remoteUrl }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: init-repo
      name: 저장소 초기화
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: wait
      name: 저장소 준비 대기
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: register
      name: 카탈로그 등록
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: 카탈로그에서 열기
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GitHub에서 열기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: GitHub Actions 보기
        icon: github
        url: ${{ steps['create-repo'].output.remoteUrl }}/actions
