---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-kr-server-tls
  namespace: backstage-kr
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: default-cert
    kind: ClusterSecretStore
  target:
    name: backstage-kr-server-tls
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: default-tls-prod
      property: tls.key
  - secretKey: tls.crt
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: default-tls-prod
      property: tls.crt
